name: Telegram Bot Rachel

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.2

      - name: Build
        run: go build -v -o TGBotRachel ./main.go

      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/Module/, /CloudFunction/"
      
      - name: Restart Rachel
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            pkill TGBotRachel
            cd ${{ secrets.REMOTE_TARGET }}
            export MASTER_ID=${{ secrets.MASTER_ID }}
            export CHANNEL_REPORT=${{ secrets.CHANNEL_REPORT }}
            export CHANNEL_SLEEP=${{ secrets.CHANNEL_SLEEP }}
            export TGBOTTOKEN=${{ secrets.TGBOTTOKEN }}
            nohup ./TGBotRachel > /dev/null   2>error.log  &